#ChallengeMode created by Sudologic
#Main Settings
autoDefaultParams: false

#SupplyDrop settings
#secondsPerDrop: How many seconds should pass between drops?
#startingBorder: Diameter of the World Border at the start of the game.
#endingBorder: Diameter of the World Border at the end of the game.
#lengthInSeconds: How long the game should run, in seconds.
#maxSlotsFull: The maximum number of slots in the chests that will be filled.
secondsPerDrop: 3600
supplyStartingBorder: 5000
supplyEndingBorder: 50
supplyLengthInSeconds: 1209600
noticeInSeconds: 300
maxSlotsFull: 28

#BorderShrink settings
#startingBorder: Diameter of the World Border at the start of the game.
#endingBorder: Diameter of the World Border at the end of the game.
#borderLengthInSeconds: How long the game should run, in seconds.
startingBorder: 5000
endingBorder: 50
borderLengthInSeconds: 1209600